theme = "gruvbox"

[editor]
color-modes = true
line-number = "relative"
mouse = false
true-color = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
