theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
color-modes = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
