[language-server.typst-lsp]
config = { exportPdf = "never" }

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "lean"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'⟨' = '⟩'
